# Generated by Django 3.1.1 on 2020-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200909_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
