# Generated by Django 3.1.1 on 2020-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('NA', 'Select a unit'), ('tbs', 'tbs'), ('tsp', 'tsp'), ('cup', 'cup'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'litre')], max_length=30),
        ),
    ]
