# Generated by Django 3.1.1 on 2020-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201013_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='header_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('NA', 'Select a unit'), ('tbs', 'tbs'), ('tsp', 'tsp'), ('cup', 'cup'), ('cups', 'cups'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'L')], max_length=30),
        ),
    ]
