# Generated by Django 3.1.1 on 2020-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20201028_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='header_image',
            field=models.ImageField(blank=True, default='default_food.jpg', null=True, upload_to='images/'),
        ),
    ]
